name: CI

on:
  push:
    branches: [ "main", "development" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main", "development" ]
    paths-ignore:
      - '**/README.md'

  
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.5.3"
    steps:
      # Checks-out repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
